ai_names = [
    "HazugCsóti",
    "Kamucsótány",
    "Lapátadó",
    "Poloskakirály",
    "Hálócsapda",
    "HazudósBélus",
    "SunyiJóska",
    "KártyásFeri",
    "LaplopóLajos",
    "BlöffBandi",
    "ÁtverőPisti",
    "ZümmZoli",
    "CsótányKarcsi",
]
